import { useCallback, useEffect, useState } from 'react';
import { Navigate } from 'react-router-dom';
import { rainApi, normalizeApiError } from '../../api/client';
import type { AdminUser, AuditLog, UserRole, UserStatus } from '../../api/types';
import { useAuth } from '../../auth/AuthContext';
import { isAdmin } from '../../auth/permissions';

export function AdminPage() {
  const auth=useAuth(); const [users,setUsers]=useState<AdminUser[]>([]); const [logs,setLogs]=useState<AuditLog[]>([]); const [query,setQuery]=useState(''); const [role,setRole]=useState<UserRole|''>(''); const [status,setStatus]=useState<UserStatus|''>(''); const [userCursor,setUserCursor]=useState<string|undefined>(); const [nextUserCursor,setNextUserCursor]=useState<string|null>(null); const [auditCursor,setAuditCursor]=useState<string|undefined>(); const [nextAuditCursor,setNextAuditCursor]=useState<string|null>(null); const [error,setError]=useState<string|null>(null); const [notice,setNotice]=useState<string|null>(null);
  const load=useCallback(async()=>{if(auth.state.status!=='AUTHENTICATED'||!isAdmin(auth.state.user))return;setError(null);try{const [u,a]=await Promise.all([rainApi.fetchAdminUsers({query:query||undefined,role:role||undefined,status:status||undefined,cursor:userCursor}),rainApi.fetchAuditLogs(auditCursor)]);setUsers(u.items);setNextUserCursor(u.next_cursor);setLogs(a.items);setNextAuditCursor(a.next_cursor);}catch(e){setError(normalizeApiError(e));}},[auth.state,query,role,status,userCursor,auditCursor]);
  useEffect(()=>{void load();},[load]);
  if(auth.state.status==='LOADING')return <p>正在确认身份…</p>;
  if(auth.state.status!=='AUTHENTICATED')return <Navigate to="/login" replace state={{from:'/admin'}} />;
  if(!isAdmin(auth.state.user))return <section className="panel"><h2>403</h2><p>此页面需要管理员权限。</p></section>;
  const act=async(action:()=>Promise<unknown>,message:string)=>{if(!window.confirm('确认执行此管理操作？'))return;setError(null);try{await action();setNotice(message);await load();await auth.refresh();}catch(e){setError(normalizeApiError(e));}};
  return <div className="space-y-5"><section className="panel space-y-3"><h2 className="text-xl font-semibold">用户管理</h2>{error?<p className="text-rose-600">{error}</p>:null}{notice?<p className="text-emerald-700">{notice}</p>:null}<div className="flex gap-2"><input className="rounded border px-3 py-2" placeholder="搜索用户名" value={query} onChange={e=>{setQuery(e.target.value);setUserCursor(undefined);}}/><select value={role} onChange={e=>{setRole(e.target.value as UserRole|'');setUserCursor(undefined);}}><option value="">全部角色</option><option>USER</option><option>ADMIN</option></select><select value={status} onChange={e=>{setStatus(e.target.value as UserStatus|'');setUserCursor(undefined);}}><option value="">全部状态</option><option>ACTIVE</option><option>DISABLED</option></select></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th>用户</th><th>角色</th><th>状态</th><th>Session</th><th>操作</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td>{user.username}</td><td>{user.role}</td><td>{user.status}</td><td>{user.active_session_count}</td><td className="space-x-2"><button onClick={()=>void act(()=>rainApi.changeUserRole(user.id,user.role==='ADMIN'?'USER':'ADMIN'),'角色已更新')}>{user.role==='ADMIN'?'降级':'提升'}</button><button onClick={()=>void act(()=>rainApi.changeUserStatus(user.id,user.status==='ACTIVE'?'DISABLED':'ACTIVE'),'状态已更新')}>{user.status==='ACTIVE'?'停用':'启用'}</button><button onClick={()=>void act(()=>rainApi.revokeUserSessions(user.id),'Session 已撤销')}>强制注销</button></td></tr>)}</tbody></table></div><div className="flex justify-end gap-2"><button disabled={!userCursor} onClick={()=>setUserCursor(undefined)}>第一页</button><button disabled={!nextUserCursor} onClick={()=>setUserCursor(nextUserCursor||undefined)}>下一页</button></div></section><section className="panel"><h2 className="text-xl font-semibold">管理员审计日志</h2><table className="mt-3 w-full text-sm"><thead><tr><th>时间</th><th>动作</th><th>目标</th><th>变化</th></tr></thead><tbody>{logs.map(log=><tr key={log.id}><td>{log.created_at}</td><td>{log.action}</td><td>{log.target_user_id||'-'}</td><td>{log.old_value||'-'} → {log.new_value||'-'}</td></tr>)}</tbody></table><div className="flex justify-end gap-2"><button disabled={!auditCursor} onClick={()=>setAuditCursor(undefined)}>第一页</button><button disabled={!nextAuditCursor} onClick={()=>setAuditCursor(nextAuditCursor||undefined)}>下一页</button></div></section></div>;
}
